<a href="https://colab.research.google.com/github/Swati-Mohanty/AI5002/blob/main/mgf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Moment 
from scipy import stats 
import numpy as np  
  
arr1 = np.array([[1, 31, 27, 13, 21, 9], 
                [8, 12, 8, 4, 7, 10]])  
   
  
print("Oth moment : \n", stats.moment(arr1, moment = 0))  

Oth moment : 
 [1. 1. 1. 1. 1. 1.]


In [4]:
# Moment  
from scipy import stats 
import numpy as np  
  
arr1 = [[1, 3, 27],  
        [3, 4, 6],  
        [7, 6, 3],  
        [3, 6, 8]]   
  
print("Oth moment : \n", stats.moment(arr1, moment = 0)) 
  
print("\n6th moment : \n", stats.moment(arr1, moment = 6)) 
  
print("\n9th moment : \n", stats.moment(arr1, moment = 9, axis = None)) 
  
print("\n12th moment : \n", stats.moment(arr1, moment = 12, axis = 1)) 
  
print("\n10th moment : \n", stats.moment(arr1, moment = 10, axis = 1)) 

Oth moment : 
 [1. 1. 1.]

6th moment : 
 [5.20609375e+02 9.13256836e+00 4.26392850e+06]

9th moment : 
 55265909588.26437

12th moment : 
 [1.53284936e+14 1.63654317e+02 8.83474172e+03 5.17842143e+04]

10th moment : 
 [5.53094361e+11 6.10464868e+01 1.64971407e+03 7.65588508e+03]


In [5]:
#1-Dimensional Data:

#Import required libraries:
from scipy import stats

#Dataset:
d = [1,2,3,4,5]

#Finding 0th moment:
print("0th Moment = ",stats.moment(d,moment=0))

#Finding 1st moment:
print("1st Moment = ",stats.moment(d,moment=1))

#Finding 2nd moment:
print("2nd Moment = ",stats.moment(d,moment=2))

#Finding 3nd moment:
print("3nd Moment = ",stats.moment(d,moment=3))

#Finding 4th moment:
print("4th Moment = ",stats.moment(d,moment=4))


#============================================================


#2-Dimensional Data:

#Import required libraries:
from scipy import stats

#Dataset:
d = [[5,6,9,11,3],[21,4,8,15,2]]

#Finding 0th moment:
print("0th Moment = ",stats.moment(d,moment=0))

#Finding 1st moment:
print("1st Moment = ",stats.moment(d,moment=1))

#Finding 2nd moment:
print("2nd Moment = ",stats.moment(d,moment=2))

#Finding 3nd moment:
print("3nd Moment = ",stats.moment(d,moment=3))

#Finding 4th moment:
print("4th Moment = ",stats.moment(d,moment=4))


#============================================================


#2-Dimensional Data:
#Set axis=1 (Horizonatal):

#Import required libraries:
from scipy import stats

#Dataset:
d = [[5,6,9,11,3],[21,4,8,15,2]]

#Finding 0th moment:
print("0th Moment = ",stats.moment(d,moment=0,axis=1))

#Finding 1st moment:
print("1st Moment = ",stats.moment(d,moment=1,axis=1))

#Finding 2nd moment:
print("2nd Moment = ",stats.moment(d,moment=2,axis=1))

#Finding 3nd moment:
print("3nd Moment = ",stats.moment(d,moment=3,axis=1))

#Finding 4th moment:
print("4th Moment = ",stats.moment(d,moment=4,axis=1))


#============================================================


#Multi-Dimensional Data:

#Import required libraries:
from scipy import stats

#Dataset:
d = [[5,6,9,11,3],
     [21,4,8,15,2],
    [15,23,42,1,36]]

#Finding 0th moment:
print("0th Moment = ",stats.moment(d,moment=0))

#Finding 1st moment:
print("1st Moment = ",stats.moment(d,moment=1))

#Finding 2nd moment:
print("2nd Moment = ",stats.moment(d,moment=2))

#Finding 3nd moment:
print("3nd Moment = ",stats.moment(d,moment=3))

#Finding 4th moment:
print("4th Moment = ",stats.moment(d,moment=4))


#============================================================


#2-Dimensional Data:
#Set axis=1 (Horizonatal):
#Higher Order Moments:

#Import required libraries:
from scipy import stats

#Dataset:
d = [[5,6,9,11,3],[21,4,8,15,2]]

#Finding 10th moment:
print("10th Moment = ",stats.moment(d,moment=10,axis=1))

#Finding 12th moment:
print("12th Moment = ",stats.moment(d,moment=12,axis=1))

0th Moment =  1.0
1st Moment =  0.0
2nd Moment =  2.0
3nd Moment =  0.0
4th Moment =  6.8
0th Moment =  [1. 1. 1. 1. 1.]
1st Moment =  [0. 0. 0. 0. 0.]
2nd Moment =  [64.    1.    0.25  4.    0.25]
3nd Moment =  [0. 0. 0. 0. 0.]
4th Moment =  [4.096e+03 1.000e+00 6.250e-02 1.600e+01 6.250e-02]
0th Moment =  [1. 1.]
1st Moment =  [0. 0.]
2nd Moment =  [ 8.16 50.  ]
3nd Moment =  [  4.704 144.   ]
4th Moment =  [ 110.8032 4134.8   ]
0th Moment =  [1. 1. 1. 1. 1.]
1st Moment =  [0. 0. 0. 0. 0.]
2nd Moment =  [ 43.55555556  72.66666667 249.55555556  34.66666667 249.55555556]
3nd Moment =  [ -84.74074074  420.         2779.25925926  -96.         2779.25925926]
4th Moment =  [ 2845.62962963  7920.66666667 93416.96296296  1802.66666667
 93416.96296296]
10th Moment =  [4.67770829e+05 5.41627985e+09]
12th Moment =  [7.84184386e+06 6.41913756e+11]
